165/aggregating reviews
loolabs/waterpark pull request #204
Opened 2021-08-11 20:25 UTC by a22yuen

## Screenshots
![image](https://user-images.githubusercontent.com/74753389/129098167-02d609f5-f3b8-4a70-8db9-47bbf3bd7805.png)

## Purpose
Closes 165

- Display aggregated reviews within each resource and on the card when in grid form for overviewing all resources

2021-08-13 01:15 UTC, jeffzh4ng requested changes
Amazing job guys, the preview looks fucking great 😍

2021-08-13 01:15 UTC, jeffzh4ng commented on client/components/common/Functions.tsx
> +export const capitalizeFirstLetter = (str: string): string => {
`/common/Functions` is somewhat of a weird name. Something like `/common/utils` might be better?

2021-08-13 01:15 UTC, jeffzh4ng commented on client/components/resource/ResourceCard.tsx
> +  console.log(resourceLookup[resourceSlug]['criteria'])
```suggestion
```

2021-08-13 01:15 UTC, jeffzh4ng commented on client/components/resource/ResourceCard.tsx
> +        {resourceLookup[resourceSlug]['criteria'].map((criteria) => (
```suggestion
        {resourceLookup[resourceSlug]['criteria'].map((criterion) => (
```

2021-08-21 21:14 UTC, xujustinj commented on client/components/resource-details/ResourceInfo.tsx
> +            <MemberCount>200-300 students</MemberCount>
TODO (not for this PR)

2021-08-21 21:18 UTC, xujustinj commented on client/styles/typography.ts
> +import { width, smallerThan, largerThan } from './device'
```suggestion
import { width, smallerThan } from './device'
```

2021-08-21 21:19 UTC, xujustinj approved these changes

2021-08-22 01:41 UTC, jeffzh4ng approved these changes
🔥

2021-08-22 01:41 UTC, jeffzh4ng commented on client/components/resource/ResourceCard.tsx
> +  // grid-template-columns: repeat(auto-fit, minmax(100px, 33%));
```suggestion
```

2021-08-22 22:36 UTC, merged