💻 Implement fuzzy search
loolabs/waterpark pull request #30
Opened 2021-02-06 19:05 UTC by lesliexin

## Purpose
As a user, I should be able to fuzzy search through club cards by their name. 

## Approach
Implemented fuzzy search using (fuse.js)[https://fusejs.io/]

![ezgif com-gif-maker](https://user-images.githubusercontent.com/18248358/107127476-566eb600-6884-11eb-896c-fa3748c047b1.gif)

2021-02-06 20:06 UTC, ShreyasPrasad reviewed
Nice use of `useMemo` for some efficiency! Clean component.

2021-02-06 20:07 UTC, ShreyasPrasad approved these changes

2021-02-06 20:35 UTC, jeffzh4ng requested changes

2021-02-06 20:35 UTC, jeffzh4ng commented on client/pages/ClubList.tsx
> +    const filteredClubs: (Fuse.FuseResult<Club> | Club)[] = searchValue ? fuse.search(searchValue) : formattedClubs;
I think our searching logic should be extracted into a hook, just to make our `ClubsList` container/page component nicer. For example, all `ClubsList` could look like this.

```
ClubsList {
  const [filteredClubs, setSearchValue] = useSearch(searchValue)

  return (
    <input onChange={(e) => setSearchValue(e.target.value)}>
    <FilteredClubsList>
  )
}
```

In my mind, these container/page components are similar to "use cases" on the backend. They are the managers that talk to the domain (hooks) and infra (react presentation components).

I created some initial ideas and guidelines we could use for client architecture here: https://www.notion.so/Architecture-63ef0af1fa7640aba6826d6664ed2642

2021-02-11 00:05 UTC, jeffzh4ng approved these changes

2021-02-11 00:06 UTC, jeffzh4ng commented
Seems like we decided on keeping the filtering logic within the component. I don't feel too strongly about pulling it out into a hook as of now, but if the component grows in the future I'm pro hook :P

2021-02-11 00:20 UTC, merged